version: "2"

com.kst.services:
  api:
    command: "scala-2.11/kafkaRestApi-assembly-1.0.0.jar kst-cognosfera/kafka-rest/loc"
    ports:
      - "9002:9002"
    external_links:
      - sandbox
    container_name: cognosfera_kafka_api
    image: dev.docker.kickstartteam.es:5000/kst/cognosfera/demo-kafka-api:0.0.1
    environment:
      CONSUL: dev.consul.kickstartteam.es:8500
      REALM: EXAMPLE.COM
      DOMAIN_REALM: node.dc1.consul
      KDC_ADDRESS: sandbox.hortonworks.com
      KDC_PORT: 88
    depends_on:
      - postgres

  postgres:
    container_name: congnosfera_postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

